apiVersion: apps/v1
kind: Deployment
metadata:
  name: <APP_NAME>
spec:
  selector:
    matchLabels:
      app: <APP_NAME>
  template:
    metadata:
      labels:
        app: <APP_NAME>
        version: <APP_TAG>
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: <APP_NAME>
          imagePullPolicy: IfNotPresent
          image: registry.cn-beijing.aliyuncs.com/coolcar-code/<APP_NAME>:<APP_TAG>
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            exec:
              command:
                - "/bin/grpc-health-probe"
                - "-addr=:8081"
            initialDelaySeconds: 5
          env:
            - name: ADDR
              value: ":8081"
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: endpoints
                  key: mongo
            - name: OSS_ADDR
              valueFrom:
                  secretKeyRef:
                    key: url
                    name: oss
            - name: OSS_ACCESS_KEY_ID
              valueFrom:
                  secretKeyRef:
                    key: oss_access_key_id
                    name: oss
            - name: OSS_SECRET_KEY
              valueFrom:
                  secretKeyRef:
                    key: oss_secret_key
                    name: oss
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: <APP_NAME>
spec:
  selector:
    app: <APP_NAME>
  ports:
    - port: 8081
      targetPort: 8081
      appProtocol: grpc
      name: grpc
      protocol: TCP
  type: ClusterIP

#    - port: 15021
#      targetPort: 15021
#      name: http
#      appProtocol: http