apiVersion: apps/v1
kind: Deployment
metadata:
  name: <APP_NAME>
spec:
  selector:
    matchLabels:
      app: <APP_NAME>
  template:
    metadata:
      labels:
        app: <APP_NAME>
        version: <APP_TAG>
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: <APP_NAME>
          imagePullPolicy: IfNotPresent
          image: registry.cn-beijing.aliyuncs.com/coolcar-code/<APP_NAME>:<APP_TAG>
          resources:
            limits:
              cpu: "30m"
              memory: "128Mi"
          livenessProbe:
            exec:
              command:
                - "/bin/grpc-health-probe"
                - "-addr=:8081"
            initialDelaySeconds: 5
          env:
            - name: ADDR
              value: ":8081"
            - name: AMQP_URL
              valueFrom:
                configMapKeyRef:
                    key: amqp
                    name: endpoints
            - name: CAR_ADDR
              valueFrom:
                configMapKeyRef:
                    key: car
                    name: endpoints
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: endpoints
                  key: mongo
            - name: TRIP_ADDR
              valueFrom:
                 configMapKeyRef:
                    key: trip
                    name: endpoints
            - name: AI_ADDR
              valueFrom:
                configMapKeyRef:
                  key: ai
                  name: endpoints
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: <APP_NAME>
spec:
  selector:
    app: <APP_NAME>
  ports:
  - name: grpc
    protocol: TCP
    port: 8081
    appProtocol: grpc
    targetPort: 8081

  - name: http
    protocol: TCP
    port: 8080
    appProtocol: http
    targetPort: 8080

#  - port: 15021
#    targetPort: 15021
#    name: http
#    protocol: TCP
#    appProtocol: http
  type: ClusterIP